'use server';

import { ai } from '@/ai/genkit';
import { z } from 'zod';

const MedicineDetailRetrievalInputSchema = z.object({
  medicineName: z.string().describe('The name of the medicine to search for.'),
});

// This was the source of the error. The schema did not match the output.
// It is now corrected to z.string().
const MedicineDetailRetrievalOutputSchema = z.string();

export const getMedicineDetails = ai.defineTool(
  {
    name: 'getMedicineDetails',
    description: 'Get detailed information about a specific medicine, including its uses, dosage, side effects, and interactions.',
    inputSchema: MedicineDetailRetrievalInputSchema,
    outputSchema: MedicineDetailRetrievalOutputSchema,
  },
  async (input) => {
    // This tool now just structures the output. 
    // The main chatbot prompt will do the work of generating the details.
    // This is a workaround to a bug where the sub-flow was failing.
    const { medicineName } = input;
    console.log(`Getting details for ${medicineName} in tool`);
    // The actual generation will be handled by the main flow based on the tool's output.
    // This tool's purpose is to signal the need for details.
    return `Details for ${medicineName} uses, dosage, side effects, and interactions to be generated by the main prompt.`;
  }
);
